# This is a basic workflow to help you get started with Actions

name: terraform-3-tier-app

#Controls when the workflow will run

on:
  push:
  pull_request:
    branches: [  ]

  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      ## install terraform
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
      ## int  tf code   
      - name: terraform init in the dir
        run: cd approach1-3-tier-tf && terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.JSONFORGCP }}
      ## plan tf code   
      - name: terraform plan in the dir
        run: cd approach1-3-tier-tf && terraform plan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.JSONFORGCP }}
      ## applying tf code     
      - name: terraform apply  in the dir
        run: cd approach1-3-tier-tf && terraform apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.JSONFORGCP }}
      - name: terraform apply  in the dir
        if: ${{ failure() }}
        run: cd approach1-3-tier-tf && terraform destroy -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.JSONFORGCP }}
      
