
name: get-metadata

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v1.1.0
      - name: Run a multi-line script
        run: |
          GCLOUD_AUTH_KEY="${{ secrets.JSONFORGCP }}"
          PROJECT_ID="taskmani-376813"
          echo "$GCLOUD_AUTH_KEY" > /tmp/gcloud-auth.json
          gcloud auth activate-service-account --key-file="/tmp/gcloud-auth.json"
          gcloud config set project "$PROJECT_ID"
          gcloud compute instances describe --zone us-west4-b instance-1 --format=json
     
          
          
